---

- name: Retrieve latest release information
  ansible.builtin.uri:
    url: https://api.github.com/repos/sgaunet/jwt-cli/releases/latest
    return_content: true
  register: project_info
  changed_when: false
  check_mode: false

- name: Override version to setup if latest
  ansible.builtin.set_fact:
    jwtcli_version: "{{ project_info.content | from_json | json_query('tag_name') | replace('v', '') }}"
  changed_when: false
  check_mode: false
  when:
    - jwtcli_version == "latest"

# - debug:
#     msg: "{{ project_info.content | from_json | json_query('tag_name') }}"

# pip3 install jmespath

- name: Check jwt-cli version
  become: false
  ansible.builtin.shell: 'set -o pipefail && jwt-cli version'
  args:
    executable: /bin/bash
  register: jwtcli_version_client_installed
  changed_when: false
  failed_when: false
  check_mode: false

- name: Check jwt-cli version # noqa command-instead-of-shell
  ansible.builtin.shell: '/bin/true'
  changed_when: jwtcli_version_client_installed.stdout != jwtcli_version
  check_mode: false

- name: Install jwt-cli
  ansible.builtin.get_url:
    url: "https://github.com/sgaunet/jwt-cli/releases/download/v{{ jwtcli_version }}/jwt-cli_{{ jwtcli_version }}_{{ jwtcli_os }}_{{ jwtcli_arch }}"
    dest: "{{ jwtcli_bin_path }}/jwt-cli"
    # avoid 304
    force: true
    mode: "0755"
  when:
    - not ansible_check_mode
    - jwtcli_version != jwtcli_version_client_installed.stdout
